// Copyright 2020 Igor Rukhovich
#ifndef MODULES_TASK_2_RUKHOVICH_I_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
#define MODULES_TASK_2_RUKHOVICH_I_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_

#include <mpi.h>

MPI_Comm make_linear_topology();

#endif  // MODULES_TASK_2_RUKHOVICH_I_LINEAR_TOPOLOGY_LINEAR_TOPOLOGY_H_
